<?php
/**
 * DevicesApi
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace ArtikCloud\Api;

use \ArtikCloud\Configuration;
use \ArtikCloud\ApiClient;
use \ArtikCloud\ApiException;
use \ArtikCloud\ObjectSerializer;

/**
 * DevicesApi Class Doc Comment
 *
 * @category Class
 * @package  ArtikCloud
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DevicesApi
{

    /**
     * API Client
     * @var \ArtikCloud\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \ArtikCloud\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://api.artik.cloud/v1.1');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \ArtikCloud\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \ArtikCloud\ApiClient $apiClient set the API client
     * @return DevicesApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * addDevice
     *
     * Add Device
     *
     * @param \ArtikCloud\Model\Device $device Device to be added to the user (required)
     * @return \ArtikCloud\Model\DeviceEnvelope
     * @throws \ArtikCloud\ApiException on non-2xx response
     */
    public function addDevice($device)
    {
        list($response, $statusCode, $httpHeader) = $this->addDeviceWithHttpInfo ($device);
        return $response; 
    }


    /**
     * addDeviceWithHttpInfo
     *
     * Add Device
     *
     * @param \ArtikCloud\Model\Device $device Device to be added to the user (required)
     * @return Array of \ArtikCloud\Model\DeviceEnvelope, HTTP status code, HTTP response headers (array of strings)
     * @throws \ArtikCloud\ApiException on non-2xx response
     */
    public function addDeviceWithHttpInfo($device)
    {
        
        // verify the required parameter 'device' is set
        if ($device === null) {
            throw new \InvalidArgumentException('Missing the required parameter $device when calling addDevice');
        }
  
        // parse inputs
        $resourcePath = "/devices";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($device)) {
            $_tempBody = $device;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\ArtikCloud\Model\DeviceEnvelope'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\ArtikCloud\ObjectSerializer::deserialize($response, '\ArtikCloud\Model\DeviceEnvelope', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            default:
                $data = \ArtikCloud\ObjectSerializer::deserialize($e->getResponseBody(), '\ArtikCloud\Model\DeviceEnvelope', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * deleteDevice
     *
     * Delete Device
     *
     * @param string $device_id deviceId (required)
     * @return \ArtikCloud\Model\DeviceEnvelope
     * @throws \ArtikCloud\ApiException on non-2xx response
     */
    public function deleteDevice($device_id)
    {
        list($response, $statusCode, $httpHeader) = $this->deleteDeviceWithHttpInfo ($device_id);
        return $response; 
    }


    /**
     * deleteDeviceWithHttpInfo
     *
     * Delete Device
     *
     * @param string $device_id deviceId (required)
     * @return Array of \ArtikCloud\Model\DeviceEnvelope, HTTP status code, HTTP response headers (array of strings)
     * @throws \ArtikCloud\ApiException on non-2xx response
     */
    public function deleteDeviceWithHttpInfo($device_id)
    {
        
        // verify the required parameter 'device_id' is set
        if ($device_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $device_id when calling deleteDevice');
        }
  
        // parse inputs
        $resourcePath = "/devices/{deviceId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($device_id !== null) {
            $resourcePath = str_replace(
                "{" . "deviceId" . "}",
                $this->apiClient->getSerializer()->toPathValue($device_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams, '\ArtikCloud\Model\DeviceEnvelope'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\ArtikCloud\ObjectSerializer::deserialize($response, '\ArtikCloud\Model\DeviceEnvelope', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            default:
                $data = \ArtikCloud\ObjectSerializer::deserialize($e->getResponseBody(), '\ArtikCloud\Model\DeviceEnvelope', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * deleteDeviceToken
     *
     * Delete Device Token
     *
     * @param string $device_id deviceId (required)
     * @return \ArtikCloud\Model\DeviceTokenEnvelope
     * @throws \ArtikCloud\ApiException on non-2xx response
     */
    public function deleteDeviceToken($device_id)
    {
        list($response, $statusCode, $httpHeader) = $this->deleteDeviceTokenWithHttpInfo ($device_id);
        return $response; 
    }


    /**
     * deleteDeviceTokenWithHttpInfo
     *
     * Delete Device Token
     *
     * @param string $device_id deviceId (required)
     * @return Array of \ArtikCloud\Model\DeviceTokenEnvelope, HTTP status code, HTTP response headers (array of strings)
     * @throws \ArtikCloud\ApiException on non-2xx response
     */
    public function deleteDeviceTokenWithHttpInfo($device_id)
    {
        
        // verify the required parameter 'device_id' is set
        if ($device_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $device_id when calling deleteDeviceToken');
        }
  
        // parse inputs
        $resourcePath = "/devices/{deviceId}/tokens";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($device_id !== null) {
            $resourcePath = str_replace(
                "{" . "deviceId" . "}",
                $this->apiClient->getSerializer()->toPathValue($device_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams, '\ArtikCloud\Model\DeviceTokenEnvelope'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\ArtikCloud\ObjectSerializer::deserialize($response, '\ArtikCloud\Model\DeviceTokenEnvelope', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            default:
                $data = \ArtikCloud\ObjectSerializer::deserialize($e->getResponseBody(), '\ArtikCloud\Model\DeviceTokenEnvelope', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getDevice
     *
     * Get Device
     *
     * @param string $device_id deviceId (required)
     * @return \ArtikCloud\Model\DeviceEnvelope
     * @throws \ArtikCloud\ApiException on non-2xx response
     */
    public function getDevice($device_id)
    {
        list($response, $statusCode, $httpHeader) = $this->getDeviceWithHttpInfo ($device_id);
        return $response; 
    }


    /**
     * getDeviceWithHttpInfo
     *
     * Get Device
     *
     * @param string $device_id deviceId (required)
     * @return Array of \ArtikCloud\Model\DeviceEnvelope, HTTP status code, HTTP response headers (array of strings)
     * @throws \ArtikCloud\ApiException on non-2xx response
     */
    public function getDeviceWithHttpInfo($device_id)
    {
        
        // verify the required parameter 'device_id' is set
        if ($device_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $device_id when calling getDevice');
        }
  
        // parse inputs
        $resourcePath = "/devices/{deviceId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($device_id !== null) {
            $resourcePath = str_replace(
                "{" . "deviceId" . "}",
                $this->apiClient->getSerializer()->toPathValue($device_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\ArtikCloud\Model\DeviceEnvelope'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\ArtikCloud\ObjectSerializer::deserialize($response, '\ArtikCloud\Model\DeviceEnvelope', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            default:
                $data = \ArtikCloud\ObjectSerializer::deserialize($e->getResponseBody(), '\ArtikCloud\Model\DeviceEnvelope', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getDeviceToken
     *
     * Get Device Token
     *
     * @param string $device_id deviceId (required)
     * @return \ArtikCloud\Model\DeviceTokenEnvelope
     * @throws \ArtikCloud\ApiException on non-2xx response
     */
    public function getDeviceToken($device_id)
    {
        list($response, $statusCode, $httpHeader) = $this->getDeviceTokenWithHttpInfo ($device_id);
        return $response; 
    }


    /**
     * getDeviceTokenWithHttpInfo
     *
     * Get Device Token
     *
     * @param string $device_id deviceId (required)
     * @return Array of \ArtikCloud\Model\DeviceTokenEnvelope, HTTP status code, HTTP response headers (array of strings)
     * @throws \ArtikCloud\ApiException on non-2xx response
     */
    public function getDeviceTokenWithHttpInfo($device_id)
    {
        
        // verify the required parameter 'device_id' is set
        if ($device_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $device_id when calling getDeviceToken');
        }
  
        // parse inputs
        $resourcePath = "/devices/{deviceId}/tokens";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($device_id !== null) {
            $resourcePath = str_replace(
                "{" . "deviceId" . "}",
                $this->apiClient->getSerializer()->toPathValue($device_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\ArtikCloud\Model\DeviceTokenEnvelope'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\ArtikCloud\ObjectSerializer::deserialize($response, '\ArtikCloud\Model\DeviceTokenEnvelope', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            default:
                $data = \ArtikCloud\ObjectSerializer::deserialize($e->getResponseBody(), '\ArtikCloud\Model\DeviceTokenEnvelope', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * updateDevice
     *
     * Update Device
     *
     * @param string $device_id deviceId (required)
     * @param \ArtikCloud\Model\Device $device Device to be updated (required)
     * @return \ArtikCloud\Model\DeviceEnvelope
     * @throws \ArtikCloud\ApiException on non-2xx response
     */
    public function updateDevice($device_id, $device)
    {
        list($response, $statusCode, $httpHeader) = $this->updateDeviceWithHttpInfo ($device_id, $device);
        return $response; 
    }


    /**
     * updateDeviceWithHttpInfo
     *
     * Update Device
     *
     * @param string $device_id deviceId (required)
     * @param \ArtikCloud\Model\Device $device Device to be updated (required)
     * @return Array of \ArtikCloud\Model\DeviceEnvelope, HTTP status code, HTTP response headers (array of strings)
     * @throws \ArtikCloud\ApiException on non-2xx response
     */
    public function updateDeviceWithHttpInfo($device_id, $device)
    {
        
        // verify the required parameter 'device_id' is set
        if ($device_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $device_id when calling updateDevice');
        }
        // verify the required parameter 'device' is set
        if ($device === null) {
            throw new \InvalidArgumentException('Missing the required parameter $device when calling updateDevice');
        }
  
        // parse inputs
        $resourcePath = "/devices/{deviceId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($device_id !== null) {
            $resourcePath = str_replace(
                "{" . "deviceId" . "}",
                $this->apiClient->getSerializer()->toPathValue($device_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($device)) {
            $_tempBody = $device;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams, '\ArtikCloud\Model\DeviceEnvelope'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\ArtikCloud\ObjectSerializer::deserialize($response, '\ArtikCloud\Model\DeviceEnvelope', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            default:
                $data = \ArtikCloud\ObjectSerializer::deserialize($e->getResponseBody(), '\ArtikCloud\Model\DeviceEnvelope', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * updateDeviceToken
     *
     * Update Device Token
     *
     * @param string $device_id deviceId (required)
     * @return \ArtikCloud\Model\DeviceTokenEnvelope
     * @throws \ArtikCloud\ApiException on non-2xx response
     */
    public function updateDeviceToken($device_id)
    {
        list($response, $statusCode, $httpHeader) = $this->updateDeviceTokenWithHttpInfo ($device_id);
        return $response; 
    }


    /**
     * updateDeviceTokenWithHttpInfo
     *
     * Update Device Token
     *
     * @param string $device_id deviceId (required)
     * @return Array of \ArtikCloud\Model\DeviceTokenEnvelope, HTTP status code, HTTP response headers (array of strings)
     * @throws \ArtikCloud\ApiException on non-2xx response
     */
    public function updateDeviceTokenWithHttpInfo($device_id)
    {
        
        // verify the required parameter 'device_id' is set
        if ($device_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $device_id when calling updateDeviceToken');
        }
  
        // parse inputs
        $resourcePath = "/devices/{deviceId}/tokens";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($device_id !== null) {
            $resourcePath = str_replace(
                "{" . "deviceId" . "}",
                $this->apiClient->getSerializer()->toPathValue($device_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams, '\ArtikCloud\Model\DeviceTokenEnvelope'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\ArtikCloud\ObjectSerializer::deserialize($response, '\ArtikCloud\Model\DeviceTokenEnvelope', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            default:
                $data = \ArtikCloud\ObjectSerializer::deserialize($e->getResponseBody(), '\ArtikCloud\Model\DeviceTokenEnvelope', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
}
