<?php
/**
 * ExportNormalizedMessagesResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARTIK Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ArtikCloud\ArtikCloud\Model;

use \ArrayAccess;

/**
 * ExportNormalizedMessagesResponse Class Doc Comment
 *
 * @category    Class
 * @description Export Normalized Messages Response.
 * @package     ArtikCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExportNormalizedMessagesResponse implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ExportNormalizedMessagesResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'csv_headers' => 'bool',
        'end_date' => 'int',
        'export_id' => 'string',
        'format' => 'string',
        'order' => 'string',
        'sdid' => 'string',
        'sdids' => 'string',
        'start_date' => 'int',
        'stdids' => 'string',
        'trial_id' => 'string',
        'uid' => 'string',
        'uids' => 'string',
        'url' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'csv_headers' => 'csvHeaders',
        'end_date' => 'endDate',
        'export_id' => 'exportId',
        'format' => 'format',
        'order' => 'order',
        'sdid' => 'sdid',
        'sdids' => 'sdids',
        'start_date' => 'startDate',
        'stdids' => 'stdids',
        'trial_id' => 'trialId',
        'uid' => 'uid',
        'uids' => 'uids',
        'url' => 'url'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'csv_headers' => 'setCsvHeaders',
        'end_date' => 'setEndDate',
        'export_id' => 'setExportId',
        'format' => 'setFormat',
        'order' => 'setOrder',
        'sdid' => 'setSdid',
        'sdids' => 'setSdids',
        'start_date' => 'setStartDate',
        'stdids' => 'setStdids',
        'trial_id' => 'setTrialId',
        'uid' => 'setUid',
        'uids' => 'setUids',
        'url' => 'setUrl'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'csv_headers' => 'getCsvHeaders',
        'end_date' => 'getEndDate',
        'export_id' => 'getExportId',
        'format' => 'getFormat',
        'order' => 'getOrder',
        'sdid' => 'getSdid',
        'sdids' => 'getSdids',
        'start_date' => 'getStartDate',
        'stdids' => 'getStdids',
        'trial_id' => 'getTrialId',
        'uid' => 'getUid',
        'uids' => 'getUids',
        'url' => 'getUrl'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['csv_headers'] = isset($data['csv_headers']) ? $data['csv_headers'] : null;
        $this->container['end_date'] = isset($data['end_date']) ? $data['end_date'] : null;
        $this->container['export_id'] = isset($data['export_id']) ? $data['export_id'] : null;
        $this->container['format'] = isset($data['format']) ? $data['format'] : null;
        $this->container['order'] = isset($data['order']) ? $data['order'] : null;
        $this->container['sdid'] = isset($data['sdid']) ? $data['sdid'] : null;
        $this->container['sdids'] = isset($data['sdids']) ? $data['sdids'] : null;
        $this->container['start_date'] = isset($data['start_date']) ? $data['start_date'] : null;
        $this->container['stdids'] = isset($data['stdids']) ? $data['stdids'] : null;
        $this->container['trial_id'] = isset($data['trial_id']) ? $data['trial_id'] : null;
        $this->container['uid'] = isset($data['uid']) ? $data['uid'] : null;
        $this->container['uids'] = isset($data['uids']) ? $data['uids'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets csv_headers
     * @return bool
     */
    public function getCsvHeaders()
    {
        return $this->container['csv_headers'];
    }

    /**
     * Sets csv_headers
     * @param bool $csv_headers
     * @return $this
     */
    public function setCsvHeaders($csv_headers)
    {
        $this->container['csv_headers'] = $csv_headers;

        return $this;
    }

    /**
     * Gets end_date
     * @return int
     */
    public function getEndDate()
    {
        return $this->container['end_date'];
    }

    /**
     * Sets end_date
     * @param int $end_date
     * @return $this
     */
    public function setEndDate($end_date)
    {
        $this->container['end_date'] = $end_date;

        return $this;
    }

    /**
     * Gets export_id
     * @return string
     */
    public function getExportId()
    {
        return $this->container['export_id'];
    }

    /**
     * Sets export_id
     * @param string $export_id
     * @return $this
     */
    public function setExportId($export_id)
    {
        $this->container['export_id'] = $export_id;

        return $this;
    }

    /**
     * Gets format
     * @return string
     */
    public function getFormat()
    {
        return $this->container['format'];
    }

    /**
     * Sets format
     * @param string $format
     * @return $this
     */
    public function setFormat($format)
    {
        $this->container['format'] = $format;

        return $this;
    }

    /**
     * Gets order
     * @return string
     */
    public function getOrder()
    {
        return $this->container['order'];
    }

    /**
     * Sets order
     * @param string $order
     * @return $this
     */
    public function setOrder($order)
    {
        $this->container['order'] = $order;

        return $this;
    }

    /**
     * Gets sdid
     * @return string
     */
    public function getSdid()
    {
        return $this->container['sdid'];
    }

    /**
     * Sets sdid
     * @param string $sdid
     * @return $this
     */
    public function setSdid($sdid)
    {
        $this->container['sdid'] = $sdid;

        return $this;
    }

    /**
     * Gets sdids
     * @return string
     */
    public function getSdids()
    {
        return $this->container['sdids'];
    }

    /**
     * Sets sdids
     * @param string $sdids
     * @return $this
     */
    public function setSdids($sdids)
    {
        $this->container['sdids'] = $sdids;

        return $this;
    }

    /**
     * Gets start_date
     * @return int
     */
    public function getStartDate()
    {
        return $this->container['start_date'];
    }

    /**
     * Sets start_date
     * @param int $start_date
     * @return $this
     */
    public function setStartDate($start_date)
    {
        $this->container['start_date'] = $start_date;

        return $this;
    }

    /**
     * Gets stdids
     * @return string
     */
    public function getStdids()
    {
        return $this->container['stdids'];
    }

    /**
     * Sets stdids
     * @param string $stdids
     * @return $this
     */
    public function setStdids($stdids)
    {
        $this->container['stdids'] = $stdids;

        return $this;
    }

    /**
     * Gets trial_id
     * @return string
     */
    public function getTrialId()
    {
        return $this->container['trial_id'];
    }

    /**
     * Sets trial_id
     * @param string $trial_id
     * @return $this
     */
    public function setTrialId($trial_id)
    {
        $this->container['trial_id'] = $trial_id;

        return $this;
    }

    /**
     * Gets uid
     * @return string
     */
    public function getUid()
    {
        return $this->container['uid'];
    }

    /**
     * Sets uid
     * @param string $uid
     * @return $this
     */
    public function setUid($uid)
    {
        $this->container['uid'] = $uid;

        return $this;
    }

    /**
     * Gets uids
     * @return string
     */
    public function getUids()
    {
        return $this->container['uids'];
    }

    /**
     * Sets uids
     * @param string $uids
     * @return $this
     */
    public function setUids($uids)
    {
        $this->container['uids'] = $uids;

        return $this;
    }

    /**
     * Gets url
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     * @param string $url
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\ArtikCloud\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\ArtikCloud\ObjectSerializer::sanitizeForSerialization($this));
    }
}


