<?php
/**
 * NormalizedAction
 *
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARTIK Cloud API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ArtikCloud\Model;

use \ArrayAccess;

/**
 * NormalizedAction Class Doc Comment
 *
 * @category    Class */
 // @description Normalized Action
/** 
 * @package     ArtikCloud
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NormalizedAction implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'NormalizedAction';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'cts' => 'int',
        'ts' => 'int',
        'mid' => 'string',
        'sdid' => 'string',
        'ddid' => 'string',
        'ddtid' => 'string',
        'uid' => 'string',
        'mv' => 'int',
        'data' => '\ArtikCloud\Model\ActionArray'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'cts' => 'cts',
        'ts' => 'ts',
        'mid' => 'mid',
        'sdid' => 'sdid',
        'ddid' => 'ddid',
        'ddtid' => 'ddtid',
        'uid' => 'uid',
        'mv' => 'mv',
        'data' => 'data'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'cts' => 'setCts',
        'ts' => 'setTs',
        'mid' => 'setMid',
        'sdid' => 'setSdid',
        'ddid' => 'setDdid',
        'ddtid' => 'setDdtid',
        'uid' => 'setUid',
        'mv' => 'setMv',
        'data' => 'setData'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'cts' => 'getCts',
        'ts' => 'getTs',
        'mid' => 'getMid',
        'sdid' => 'getSdid',
        'ddid' => 'getDdid',
        'ddtid' => 'getDdtid',
        'uid' => 'getUid',
        'mv' => 'getMv',
        'data' => 'getData'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['cts'] = isset($data['cts']) ? $data['cts'] : null;
        $this->container['ts'] = isset($data['ts']) ? $data['ts'] : null;
        $this->container['mid'] = isset($data['mid']) ? $data['mid'] : null;
        $this->container['sdid'] = isset($data['sdid']) ? $data['sdid'] : null;
        $this->container['ddid'] = isset($data['ddid']) ? $data['ddid'] : null;
        $this->container['ddtid'] = isset($data['ddtid']) ? $data['ddtid'] : null;
        $this->container['uid'] = isset($data['uid']) ? $data['uid'] : null;
        $this->container['mv'] = isset($data['mv']) ? $data['mv'] : null;
        $this->container['data'] = isset($data['data']) ? $data['data'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['cts'] === null) {
            $invalid_properties[] = "'cts' can't be null";
        }
        if ($this->container['ts'] === null) {
            $invalid_properties[] = "'ts' can't be null";
        }
        if ($this->container['mid'] === null) {
            $invalid_properties[] = "'mid' can't be null";
        }
        if ($this->container['ddid'] === null) {
            $invalid_properties[] = "'ddid' can't be null";
        }
        if ($this->container['ddtid'] === null) {
            $invalid_properties[] = "'ddtid' can't be null";
        }
        if ($this->container['uid'] === null) {
            $invalid_properties[] = "'uid' can't be null";
        }
        if ($this->container['mv'] === null) {
            $invalid_properties[] = "'mv' can't be null";
        }
        if ($this->container['data'] === null) {
            $invalid_properties[] = "'data' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['cts'] === null) {
            return false;
        }
        if ($this->container['ts'] === null) {
            return false;
        }
        if ($this->container['mid'] === null) {
            return false;
        }
        if ($this->container['ddid'] === null) {
            return false;
        }
        if ($this->container['ddtid'] === null) {
            return false;
        }
        if ($this->container['uid'] === null) {
            return false;
        }
        if ($this->container['mv'] === null) {
            return false;
        }
        if ($this->container['data'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets cts
     * @return int
     */
    public function getCts()
    {
        return $this->container['cts'];
    }

    /**
     * Sets cts
     * @param int $cts
     * @return $this
     */
    public function setCts($cts)
    {
        $this->container['cts'] = $cts;

        return $this;
    }

    /**
     * Gets ts
     * @return int
     */
    public function getTs()
    {
        return $this->container['ts'];
    }

    /**
     * Sets ts
     * @param int $ts
     * @return $this
     */
    public function setTs($ts)
    {
        $this->container['ts'] = $ts;

        return $this;
    }

    /**
     * Gets mid
     * @return string
     */
    public function getMid()
    {
        return $this->container['mid'];
    }

    /**
     * Sets mid
     * @param string $mid
     * @return $this
     */
    public function setMid($mid)
    {
        $this->container['mid'] = $mid;

        return $this;
    }

    /**
     * Gets sdid
     * @return string
     */
    public function getSdid()
    {
        return $this->container['sdid'];
    }

    /**
     * Sets sdid
     * @param string $sdid
     * @return $this
     */
    public function setSdid($sdid)
    {
        $this->container['sdid'] = $sdid;

        return $this;
    }

    /**
     * Gets ddid
     * @return string
     */
    public function getDdid()
    {
        return $this->container['ddid'];
    }

    /**
     * Sets ddid
     * @param string $ddid
     * @return $this
     */
    public function setDdid($ddid)
    {
        $this->container['ddid'] = $ddid;

        return $this;
    }

    /**
     * Gets ddtid
     * @return string
     */
    public function getDdtid()
    {
        return $this->container['ddtid'];
    }

    /**
     * Sets ddtid
     * @param string $ddtid
     * @return $this
     */
    public function setDdtid($ddtid)
    {
        $this->container['ddtid'] = $ddtid;

        return $this;
    }

    /**
     * Gets uid
     * @return string
     */
    public function getUid()
    {
        return $this->container['uid'];
    }

    /**
     * Sets uid
     * @param string $uid
     * @return $this
     */
    public function setUid($uid)
    {
        $this->container['uid'] = $uid;

        return $this;
    }

    /**
     * Gets mv
     * @return int
     */
    public function getMv()
    {
        return $this->container['mv'];
    }

    /**
     * Sets mv
     * @param int $mv
     * @return $this
     */
    public function setMv($mv)
    {
        $this->container['mv'] = $mv;

        return $this;
    }

    /**
     * Gets data
     * @return \ArtikCloud\Model\ActionArray
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     * @param \ArtikCloud\Model\ActionArray $data
     * @return $this
     */
    public function setData($data)
    {
        $this->container['data'] = $data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\ArtikCloud\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\ArtikCloud\ObjectSerializer::sanitizeForSerialization($this));
    }
}


