<?php
/**
 * Artik Properties
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARTIK Cloud API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

    $config = [
        'user1' => [
            'id' => '04ddbd35d57d4d7b8f07f219c44457b2',
            'name' => 'maneesh',
            'fullname' => 'Maneesh Sahu',
            'token' => '369d8f0f5f50483fa1c46b12e5991d84',
            'email' => 'maneesh.sahu@ssi.samsung.com',
            'aid' => 'b6951bf387b84f63b38911ae35d65e28',
            'createdon' => '1406839290000',
        ],

        'device1' => [
            'id' => '19da42ee01414722a6ad1224097c38d4',
            'token' => 'dc43d12e2b59495daf94631e6ddfe3e8',
        ],

        'device2' => [
            'id' => '16f54be9b9ce4c69be14a6c8ff33ea8d',
            'token' => 'f9f75bd0b0fc46a9a604703909f4331d',
        ],

        'device3' => [
            'id' => '3dd34bce025a4409ac1ff80be81b8dbc',
            'token' => '49db2612c46342458b61af535921bdca',
        ],

        // TV
        'device4' => [
            'id' => '5c97745b1e7a4beb96edd583ad595884',
            'token' => '56482b3f3ca948d3bc8769a003bfeb7f',
        ],
    ];

    return $config;
