<?php
/**
 * UsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

require_once('autoload.php');

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  ArtikCloud
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UsersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    /**
     * Test case for getSelf
     *
     * Get Current User Profile
     *
     */
    public function test_getSelf() {
      $api_client = new ArtikCloud\ApiClient();
      $api_client->getConfig()->setHost('https://api.artik.cloud/v1.1');
      $api_client->getConfig()->setAccessToken('2fd493b9877e48bd9fe699deb1e07003');
      $users_api = new ArtikCloud\Api\UsersApi($api_client);

      $response = $users_api->getSelf();
        $this->assertInstanceOf('ArtikCloud\Model\UserEnvelope', $response);
        $this->assertSame($response->getData()->getName(), 'maneesh');
        $this->assertSame($response->getData()->getFullName(), 'Maneesh Sahu');
    }

    /**
     * Test case for getUserDevices
     *
     * Get User Devices
     *
     */
    public function test_getUserDevices() {
      $api_client = new ArtikCloud\ApiClient();
      $api_client->getConfig()->setHost('https://api.artik.cloud/v1.1');
      $api_client->getConfig()->setAccessToken('2fd493b9877e48bd9fe699deb1e07003');
      $users_api = new ArtikCloud\Api\UsersApi($api_client);

      $user_id = '04ddbd35d57d4d7b8f07f219c44457b2';

      $response = $users_api->getUserDevices($user_id);
        $this->assertInstanceOf('ArtikCloud\Model\DevicesEnvelope', $response);
    }

}
