<?php
/**
 * ActionInTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARTIK Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ArtikCloud;

/**
 * ActionInTest Class Doc Comment
 *
 * @category    Class */
// * @description Action sent to a WebSocket.
/**
 * @package     ArtikCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ActionInTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ActionIn"
     */
    public function testActionIn()
    {

    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {

    }

    /**
     * Test attribute "cid"
     */
    public function testPropertyCid()
    {

    }

    /**
     * Test attribute "ddid"
     */
    public function testPropertyDdid()
    {

    }

    /**
     * Test attribute "sdid"
     */
    public function testPropertySdid()
    {

    }

    /**
     * Test attribute "ts"
     */
    public function testPropertyTs()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

}
