<?php
/**
 * AggregateDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARTIK Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ArtikCloud;

/**
 * AggregateDataTest Class Doc Comment
 *
 * @category    Class */
// * @description Aggregate Data
/**
 * @package     ArtikCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AggregateDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AggregateData"
     */
    public function testAggregateData()
    {

    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {

    }

    /**
     * Test attribute "max"
     */
    public function testPropertyMax()
    {

    }

    /**
     * Test attribute "mean"
     */
    public function testPropertyMean()
    {

    }

    /**
     * Test attribute "min"
     */
    public function testPropertyMin()
    {

    }

    /**
     * Test attribute "sum"
     */
    public function testPropertySum()
    {

    }

    /**
     * Test attribute "variance"
     */
    public function testPropertyVariance()
    {

    }

}
