<?php
/**
 * DeviceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARTIK Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ArtikCloud;

/**
 * DeviceTest Class Doc Comment
 *
 * @category    Class */
// * @description Device information.
/**
 * @package     ArtikCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DeviceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Device"
     */
    public function testDevice()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {

    }

    /**
     * Test attribute "dtid"
     */
    public function testPropertyDtid()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "manifest_version"
     */
    public function testPropertyManifestVersion()
    {

    }

    /**
     * Test attribute "manifest_version_policy"
     */
    public function testPropertyManifestVersionPolicy()
    {

    }

    /**
     * Test attribute "need_provider_auth"
     */
    public function testPropertyNeedProviderAuth()
    {

    }

    /**
     * Test attribute "properties"
     */
    public function testPropertyProperties()
    {

    }

    /**
     * Test attribute "created_on"
     */
    public function testPropertyCreatedOn()
    {

    }

    /**
     * Test attribute "connected"
     */
    public function testPropertyConnected()
    {

    }

    /**
     * Test attribute "certificate_info"
     */
    public function testPropertyCertificateInfo()
    {

    }

    /**
     * Test attribute "certificate_signature"
     */
    public function testPropertyCertificateSignature()
    {

    }

    /**
     * Test attribute "eid"
     */
    public function testPropertyEid()
    {

    }

    /**
     * Test attribute "provider_credentials"
     */
    public function testPropertyProviderCredentials()
    {

    }

}
