<?php
/**
 * ExportNormalizedMessagesResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARTIK Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ArtikCloud;

/**
 * ExportNormalizedMessagesResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description Export Normalized Messages Response.
/**
 * @package     ArtikCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExportNormalizedMessagesResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ExportNormalizedMessagesResponse"
     */
    public function testExportNormalizedMessagesResponse()
    {

    }

    /**
     * Test attribute "csv_headers"
     */
    public function testPropertyCsvHeaders()
    {

    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {

    }

    /**
     * Test attribute "export_id"
     */
    public function testPropertyExportId()
    {

    }

    /**
     * Test attribute "format"
     */
    public function testPropertyFormat()
    {

    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {

    }

    /**
     * Test attribute "sdid"
     */
    public function testPropertySdid()
    {

    }

    /**
     * Test attribute "sdids"
     */
    public function testPropertySdids()
    {

    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {

    }

    /**
     * Test attribute "stdids"
     */
    public function testPropertyStdids()
    {

    }

    /**
     * Test attribute "trial_id"
     */
    public function testPropertyTrialId()
    {

    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {

    }

    /**
     * Test attribute "uids"
     */
    public function testPropertyUids()
    {

    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {

    }

}
