<?php
/**
 * NotifMessageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARTIK Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ArtikCloud;

/**
 * NotifMessageTest Class Doc Comment
 *
 * @category    Class */
// * @description 
/**
 * @package     ArtikCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NotifMessageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "NotifMessage"
     */
    public function testNotifMessage()
    {

    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {

    }

    /**
     * Test attribute "cts"
     */
    public function testPropertyCts()
    {

    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {

    }

    /**
     * Test attribute "mid"
     */
    public function testPropertyMid()
    {

    }

    /**
     * Test attribute "sdid"
     */
    public function testPropertySdid()
    {

    }

    /**
     * Test attribute "mv"
     */
    public function testPropertyMv()
    {

    }

    /**
     * Test attribute "sdtid"
     */
    public function testPropertySdtid()
    {

    }

    /**
     * Test attribute "ts"
     */
    public function testPropertyTs()
    {

    }

}
