<?php
/**
 * SubscriptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARTIK Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ArtikCloud;

/**
 * SubscriptionTest Class Doc Comment
 *
 * @category    Class */
// * @description 
/**
 * @package     ArtikCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Subscription"
     */
    public function testSubscription()
    {

    }

    /**
     * Test attribute "aws_region"
     */
    public function testPropertyAwsRegion()
    {

    }

    /**
     * Test attribute "include_shared_devices"
     */
    public function testPropertyIncludeSharedDevices()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "aws_key"
     */
    public function testPropertyAwsKey()
    {

    }

    /**
     * Test attribute "aws_secret"
     */
    public function testPropertyAwsSecret()
    {

    }

    /**
     * Test attribute "created_on"
     */
    public function testPropertyCreatedOn()
    {

    }

    /**
     * Test attribute "aws_kinesis_stream_name"
     */
    public function testPropertyAwsKinesisStreamName()
    {

    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {

    }

    /**
     * Test attribute "message_type"
     */
    public function testPropertyMessageType()
    {

    }

    /**
     * Test attribute "ddid"
     */
    public function testPropertyDdid()
    {

    }

    /**
     * Test attribute "subscription_type"
     */
    public function testPropertySubscriptionType()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "sdid"
     */
    public function testPropertySdid()
    {

    }

    /**
     * Test attribute "callback_url"
     */
    public function testPropertyCallbackUrl()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "aid"
     */
    public function testPropertyAid()
    {

    }

    /**
     * Test attribute "sdtid"
     */
    public function testPropertySdtid()
    {

    }

}
