<?php
/**
 * DevicesManagementApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARTIK Cloud API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ArtikCloud;

use \ArtikCloud\Configuration;
use \ArtikCloud\ApiClient;
use \ArtikCloud\ApiException;
use \ArtikCloud\ObjectSerializer;

/**
 * DevicesManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  ArtikCloud
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DevicesManagementApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createTasks
     *
     * Create a new task for one or more devices.
     *
     */
    public function testCreateTasks()
    {

    }

    /**
     * Test case for deleteServerProperties
     *
     * Deletes a device's properties..
     *
     */
    public function testDeleteServerProperties()
    {

    }

    /**
     * Test case for getAllByDid
     *
     * Returns the list of tasks for a particular device id with optional status filter..
     *
     */
    public function testGetAllByDid()
    {

    }

    /**
     * Test case for getDeviceTypesInfo
     *
     * Read a device type device management information..
     *
     */
    public function testGetDeviceTypesInfo()
    {

    }

    /**
     * Test case for getManifestProperties
     *
     * Get a device type's device management manifest properties.
     *
     */
    public function testGetManifestProperties()
    {

    }

    /**
     * Test case for getProperties
     *
     * Read a device's properties..
     *
     */
    public function testGetProperties()
    {

    }

    /**
     * Test case for getStatuses
     *
     * Returns the details and status of a task id and the individual statuses of each device id in the list..
     *
     */
    public function testGetStatuses()
    {

    }

    /**
     * Test case for getStatusesHistory
     *
     * Returns the history of the status changes for a specific task id, or for a specific device id in that task..
     *
     */
    public function testGetStatusesHistory()
    {

    }

    /**
     * Test case for getTaskByID
     *
     * Returns the details and global status of a specific task id..
     *
     */
    public function testGetTaskByID()
    {

    }

    /**
     * Test case for getTasks
     *
     * Returns the all the tasks for a device type..
     *
     */
    public function testGetTasks()
    {

    }

    /**
     * Test case for queryProperties
     *
     * Query device properties across devices..
     *
     */
    public function testQueryProperties()
    {

    }

    /**
     * Test case for updateDeviceTypesInfo
     *
     * Updates a device type information.
     *
     */
    public function testUpdateDeviceTypesInfo()
    {

    }

    /**
     * Test case for updateServerProperties
     *
     * Updates a device's server properties..
     *
     */
    public function testUpdateServerProperties()
    {

    }

    /**
     * Test case for updateTask
     *
     * Updates a task for all devices - For now just allows changing the state to cancelled..
     *
     */
    public function testUpdateTask()
    {

    }

    /**
     * Test case for updateTaskForDevice
     *
     * Updates a task for a specific device - For now just allows changing the state to cancelled..
     *
     */
    public function testUpdateTaskForDevice()
    {

    }

}
