<?php
/**
 * MonetizationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARTIK Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ArtikCloud;

use \ArtikCloud\Configuration;
use \ArtikCloud\ApiClient;
use \ArtikCloud\ApiException;
use \ArtikCloud\ObjectSerializer;

/**
 * MonetizationApiTest Class Doc Comment
 *
 * @category Class
 * @package  ArtikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MonetizationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createPricingTiers
     *
     * Define devicetype's pricing tiers..
     *
     */
    public function testCreatePricingTiers()
    {

    }

    /**
     * Test case for getPricingTiers
     *
     * Get a device's pricing tiers.
     *
     */
    public function testGetPricingTiers()
    {

    }

    /**
     * Test case for getThePricingTiers
     *
     * Get devicetype's pricing tiers..
     *
     */
    public function testGetThePricingTiers()
    {

    }

    /**
     * Test case for getUpgradePath
     *
     * Get upgrade path.
     *
     */
    public function testGetUpgradePath()
    {

    }

    /**
     * Test case for setPricingTier
     *
     * Set a device's pricing tier.
     *
     */
    public function testSetPricingTier()
    {

    }

}
