<?php
/**
 * SubscriptionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARTIK Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ArtikCloud;

use \ArtikCloud\Configuration;
use \ArtikCloud\ApiClient;
use \ArtikCloud\ApiException;
use \ArtikCloud\ObjectSerializer;

/**
 * SubscriptionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ArtikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createSubscription
     *
     * Create Subscription.
     *
     */
    public function testCreateSubscription()
    {

    }

    /**
     * Test case for deleteSubscription
     *
     * Delete Subscription.
     *
     */
    public function testDeleteSubscription()
    {

    }

    /**
     * Test case for getAllSubscriptions
     *
     * Get All Subscriptions.
     *
     */
    public function testGetAllSubscriptions()
    {

    }

    /**
     * Test case for getMessages
     *
     * Get Messages.
     *
     */
    public function testGetMessages()
    {

    }

    /**
     * Test case for getSubscription
     *
     * Get Subscription.
     *
     */
    public function testGetSubscription()
    {

    }

    /**
     * Test case for validateSubscription
     *
     * Validate Subscription.
     *
     */
    public function testValidateSubscription()
    {

    }

}
