<?php
/**
 * WhitelistingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ArtikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARTIK Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ArtikCloud;

use \ArtikCloud\Configuration;
use \ArtikCloud\ApiClient;
use \ArtikCloud\ApiException;
use \ArtikCloud\ObjectSerializer;

/**
 * WhitelistingApiTest Class Doc Comment
 *
 * @category Class
 * @package  ArtikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WhitelistingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for deleteVdid
     *
     * Delete a vdid from the devicetype whitelist..
     *
     */
    public function testDeleteVdid()
    {

    }

    /**
     * Test case for deleteWhitelistCertificate
     *
     * Delete a whitelist certificate associated with a devicetype..
     *
     */
    public function testDeleteWhitelistCertificate()
    {

    }

    /**
     * Test case for enableWhitelist
     *
     * Enable or disble whitelist feature of a device type.
     *
     */
    public function testEnableWhitelist()
    {

    }

    /**
     * Test case for getRejectedRowList
     *
     * Get the list of rejected rows for an uploaded CSV file..
     *
     */
    public function testGetRejectedRowList()
    {

    }

    /**
     * Test case for getUploadStatus
     *
     * Get the status of a uploaded CSV file..
     *
     */
    public function testGetUploadStatus()
    {

    }

    /**
     * Test case for getWhitelist
     *
     * Get whitelisted vdids of a device type..
     *
     */
    public function testGetWhitelist()
    {

    }

    /**
     * Test case for getWhitelistCertificate
     *
     * Get whitelist certificate of device type..
     *
     */
    public function testGetWhitelistCertificate()
    {

    }

    /**
     * Test case for getWhitelistStatus
     *
     * Get the status of whitelist feature (enabled/disabled) of a device type..
     *
     */
    public function testGetWhitelistStatus()
    {

    }

    /**
     * Test case for uploadCSV
     *
     * Upload a CSV file related to the Device Type..
     *
     */
    public function testUploadCSV()
    {

    }

}
